---
apiVersion: v1
kind: Namespace
metadata:
  name: bk1
  labels:
    app: debug-pod
---    
apiVersion: v1
kind: Pod
metadata:
  namespace: bk1
  name: pv-debug-pod
spec:
  containers:
  - image: quay.io/borland6/ub1804-tools
    imagePullPolicy: Always
    name: debug-pod
    volumeMounts:
      - mountPath: /test
        name: data-pvc
  volumes:
  - name: data-pvc
    persistentVolumeClaim:
      claimName: pvc-nfs
